version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8082:80"
    volumes:
      - .:/home/demo
      - /home/demo/vendor
    networks:
      - backend

  mysql-db:
    image: mysql:5.7
    platform: linux/amd64
    container_name: mysql-db
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=grevo_booting_dev
    ports:
      - 3307:3306
    volumes:
      - ./mysql:/var/lib/mysql
    networks:
      - backend

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    platform: linux/amd64
    ports:
      - "8081:80"
    environment:
      - PMA_HOST=mysql-db
    networks:
      - backend

  proxy:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "8080:80"
    depends_on:
      - app
      - phpmyadmin
    networks:
      - backend

networks:
  backend:
    driver: bridge